version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: new_acis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: new_acis_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    container_name: new_acis_server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env.dev
    environment:
      - DB_HOST=postgres
      - ALLERGEN_FILTER_AI_API_URL=http://model:7111
    depends_on:
      - postgres
      - model
  model:
    image: aikidoaikido115/new-acis-ai:1.0.1
    container_name: new_acis_ai
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 7111
    ports:
      - "7111:7111"
    expose:
      - "7111"
volumes:
  postgres_data:
    driver: local
