version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: new_acis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: new_acis_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    container_name: new_acis_server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
